
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t(self):

    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("/")
    # 2 | setWindowSize | 945x1012 | 
    self.driver.set_window_size(945, 1012)
    # 3 | click | css=.mr-2 > .ml-2 | 
    self.driver.find_element(By.CSS_SELECTOR, ".mr-2 > .ml-2").click()

    self.driver.find_element(By.ID, "user_login").send_keys("")
 
    self.driver.find_element(By.ID, "user_password").send_keys("")
    # 6 | sendKeys | id=user_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "user_password").send_keys(Keys.ENTER)
    # 7 | type | id=user_otp_attempt | 5
    self.driver.find_element(By.ID, "user_otp_attempt").send_keys("5")
    # 8 | type | css=.input:nth-child(3) #user_otp_attempt | 6
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(3) #user_otp_attempt").send_keys("6")
    # 9 | type | css=.input:nth-child(4) #user_otp_attempt | 2
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(4) #user_otp_attempt").send_keys("2")
    # 10 | type | css=.input:nth-child(5) #user_otp_attempt | 0
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(5) #user_otp_attempt").send_keys("0")
    # 11 | type | css=.input:nth-child(6) #user_otp_attempt | 3
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(6) #user_otp_attempt").send_keys("3")
    # 12 | click | css=.xs\3Apx-6:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".xs\\3Apx-ild(3)").click()
    # 13 | click | name=submit_code | 
    self.driver.find_element(By.NAME, "submit_code").click()
    # 14 | click | name=q | 
    self.driver.find_element(By.NAME, "q").click()
    # 15 | type | name=q | play room
    self.driver.find_element(By.NAME, "q").send_keys("")
    # 16 | sendKeys | name=q | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    # 17 | click | css=.inlchild(6) .py-1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".inlld(6) .py-1").click()
    # 18 | click | css=.mb-2:nth-child(2) .block > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2span").click()
    # 19 | click | css=.textnth-child(3) > .border-x .hidden | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-gray-en").click()
    # 20 | click | css=.lg\3Apr-3\.5 | 
    self.driver.find_element(By.CSS_SELECTOR, ".l5").click()
    # 21 | click | css=.pl-1:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".p(2)").click()
    # 22 | type | id=q | ab
    self.driver.find_element(By.ID, "q").send_keys("ab")
    # 23 | sendKeys | id=q | ${KEY_ENTER}
    self.driver.find_element(By.ID, "q").send_keys(Keys.ENTER)
    # 24 | click | linkText=21 | 
    self.driver.find_element(By.LINK_TEXT, "21").click()
    # 25 | close |  | 
    self.driver.close()

  
