# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_f2(self):
    self.driver.get("")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.CSS_SELECTOR, ".mr-2 > .ml-2").click()
    self.driver.find_element(By.ID, "user_login").click()
    self.driver.find_element(By.ID, "user_login").send_keys("")
    self.driver.find_element(By.ID, "user_password").send_keys("")
    self.driver.find_element(By.ID, "user_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "user_otp_attempt").send_keys("5")
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(2) #user_otp_attempt").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(3) #user_otp_attempt").send_keys("7")
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(4) #user_otp_attempt").send_keys("0")
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(5) #user_otp_attempt").send_keys("0")
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(6) #user_otp_attempt").send_keys("0")
    self.driver.find_element(By.NAME, "submit_code").click()
    self.driver.find_element(By.CSS_SELECTOR, ".inline-block > .relative").click()
    self.driver.find_element(By.ID, "q").click()
    self.driver.find_element(By.ID, "q").send_keys(" ")
    self.driver.find_element(By.ID, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".inline-block:nth-child(6) .py-1").click()
    self.driver.find_element(By.LINK_TEXT, "").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-gray-400dden").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pl-1:nth-child(2)").click()
    self.driver.find_element(By.ID, "q").send_keys("ab")
    self.driver.find_element(By.ID, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "21").click()
  
